---
- hosts: localhost
  connection: local

  become: yes
  become_method: sudo

  # vars_files:
  #   - vars.yml

  tasks:
    - debug: msg=hello
    - include: tasks/install-essential.yml
    - include: tasks/install-tools.yml
    - include: tasks/install-misc.yml
    - include: tasks/install-internet.yml
    - include: tasks/install-python.yml
    - include: tasks/install-de.yml
    - include: tasks/install-dev.yml
    - include: tasks/install-media.yml
    - include: tasks/install-tex.yml
  #   - include: tasks/base.yml tags=base
  #   - include: tasks/apps.yml tags=apps
  #   - include: tasks/zsh.yml tags=zsh
  #   - include: tasks/backup_sys.yml tags=backup
  #   - include: tasks/emacs-snapshot.yml tags=emacs
  #   - include: tasks/desktop.yml tags=desktop
  #   - include: tasks/vbox.yml tags=vbox

# - hosts: localhost
#   connection: local
#   sudo: no

#   vars_files:
#     - vars.yml

#   tasks:
#     - include: tasks/dotfiles.yml tags=dotfiles
#     - include: tasks/backup.yml tags=backup