---
- apt_repository:
    repo: "ppa:gencfsm/ppa" # for gnome-encfs-manager

- apt:
    name: "{{ item }}"
  with_items:
    - encfs
    - gnome-encfs-manager
    - ecryptfs-utils

# - name: install miscellaneous software
#   apt:
#     name: "{{ item }}"
#     state: installed
#   with_items:
#     - gdebi
#     - y-ppa-manager
#     - ppa-purge
#     - apt-file

#     - gparted
#     - unetbootin

#     - backintime-gnome # backup tool

#     - crudini # ini files manipulation

#     - gnupg1-curl", # for fetching APT keys over HTTPS

#     # not available on 16.10?
#     # "gnome-schedule", # GUI for Cron

#     