---
- apt_repository:
    repo: 'ppa:alexx2000/doublecmd'

- apt:
    name: doublecmd-gtk

- apt:
    pkg: "{{ item }}"
  with_items:
    - hunspell
    - hunspell-ru

    - pdfshuffler # GUI for shuffling and merging PDF files
    - markdown

    - motion