---
- name: install repo for gnome-encfs-manager
  apt_repository:
    repo: "ppa:gencfsm/ppa"
- name: install crypto tools
  apt:
    name: "{{ item }}"
  with_items:
    - encfs
    - ecryptfs-utils
    - gnome-encfs-manager


- name: install repo for y-ppa-manager
  apt_repository:
    repo: "ppa:webupd8team/y-ppa-manager"
- name: install package management software
  apt:
    name: "{{ item }}"
  with_items:
    - y-ppa-manager
    - gdebi
    - ppa-purge
    - apt-file


- apt:
    name: "{{ item }}"
  with_items:
    - gparted
    - unetbootin
    - backintime-gnome # backup tool
    - crudini # ini files manipulation
    - gnupg1-curl # for fetching APT keys over HTTPS
    - mutt # cli mail client

    - virtualbox
    - virtualbox-guest-additions-iso # shared folder
    - virtualbox-guest-dkms
    - virtualbox-guest-utils # necessary for high resolution for some reason
    - virtualbox-guest-x11

    - wine-stable

    # "gconf-editor",
    # "gnome-schedule", # GUI for Cron # TODO not available since16.10?