---
- apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

- apt:
    name: google-chrome-stable
    
- apt:
    name: "{{ item }}"
  with_items:
    - skype # TODO needs restricted repo?

    - caja-dropbox

    - qbittorrent
    - youtube-dl # TODO ppa? or just use scirpt?

    - samba

    - openvpn
    - rdesktop

# 'chromium-browser', TODO
# scudcloud # for Slack
# 'pidgin', 'pidgin-themes',

# 'dropbox',
# 'yandex-disk', 'yd-tools',