---
- name: install media & entertainment software
  apt:
    name: "{{ item }}"
  with_items:
    - ubuntu-restricted-extras
    - mencoder
    - mediainfo
    # arista
    # gnome-user-share

    # dia
    - inkscape
    - pinta

    - easytag
    - picard

    - radiotray

    - recordmydesktop
    - gtk-recordmydesktop
    
    - vlc

    - rhythmbox
    - rhythmbox-plugins
    # banshee

    - shutter
    - moc

    - calibre # library manager